name: "Check for Text in Pull Request"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-text:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Fetch pull request details
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return pr.data;

      - name: Check for required text in PR description
        id: check_text
        run: |
          REQUIRED_TEXTS=("unit tests added" "documentation updated")
          for text in "${REQUIRED_TEXTS[@]}"; do
            if [[ "${{ steps.pr.outputs.body }}" != *"$text"* ]]; then
              echo "Error: Missing required text '$text' in the PR description. ${{ steps.pr.outputs.body }}"
              exit 1
            fi
          done

      - name: Set success status
        if: ${{ success() }}
        run: echo "All required texts found in PR description."
